!configuration.Configuration
binSet: 
-  binsNumber: 12
   costFuntionParameters: 
   - 12.0
   - 55.0
   costFuntionType: 1
   distribution: 6
   distributionParameters: 
   - 50.0
   - 70.0
   - 90.0
   - 110.0
   - 130.0
   - 160.0
   - 190.0
   - 210.0
   - 230.0
   - 260.0
   - 290.0
   - 310.0
   lowerBoundType: 1
-  binsNumber: 12
   costFuntionParameters: 
   - 12.0
   - 55.0
   costFuntionType: 2
   distribution: 5
   distributionParameters: 
   - 50.0
   - 20.0
   lowerBoundType: 1
-  binsNumber: 12
   costFuntionType: 3
   distribution: 5
   distributionParameters: 
   - 50.0
   - 20.0
   lowerBoundType: 1
-  binsNumber: 12
   costFuntionType: 4
   distribution: 5
   distributionParameters: 
   - 50.0
   - 20.0
   lowerBoundType: 1
-  binsNumber: 55
   costFuntionParameters: 
   - 12.0
   - 55.0
   costFuntionType: 1
   distribution: 5
   distributionParameters: 
   - 75.0
   - 10.0
   lowerBoundParameters: 
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   lowerBoundType: 3
-  binsNumber: 55
   costFuntionParameters: 
   - 12.0
   - 55.0
   costFuntionType: 2
   distribution: 5
   distributionParameters: 
   - 75.0
   - 10.0
   lowerBoundParameters: 
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   lowerBoundType: 3
-  binsNumber: 55
   costFuntionType: 3
   distribution: 5
   distributionParameters: 
   - 75.0
   - 10.0
   lowerBoundParameters: 
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   lowerBoundType: 3
-  binsNumber: 55
   costFuntionType: 4
   distribution: 5
   distributionParameters: 
   - 75.0
   - 10.0
   lowerBoundParameters: 
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   - 1
   lowerBoundType: 3
binsSetsNumber: 8
itemsBySets: 
-  distribution: 1
   itemsNumber: 200
   rangeEnd: 150.0
   rangeInit: 20.0
-  distribution: 1
   itemsNumber: 500
   rangeEnd: 150.0
   rangeInit: 20.0
-  distribution: 1
   itemsNumber: 1000
   rangeEnd: 150.0
   rangeInit: 20.0
-  distribution: 1
   itemsNumber: 2000
   rangeEnd: 150.0
   rangeInit: 20.0
itemsSetsNumber: 4
