!configuration.Configuration
binSet: 
-  UpperBoundType: 1
   binsNumber: 3
   costFuntionParameters: 
   - 1.0
   - 10.0
   costFuntionType: 1
   distribution: 6
   distributionParameters: 
   - 50.0
   - 100.0
   - 120.0
binsSetsNumber: 1
itemsBySets: 
-  distribution: 1
   itemsNumber: 25
   rangeEnd: 100.0
   rangeInit: 1.0
itemsSetsNumber: 1
