!configuration.Configuration
binSet: 
-  binsNumber: 3
   costFuntionParameters: 
   - 14.0
   - 50.0
   costFuntionType: 2
   distribution: 6
   distributionParameters: 
   - 50.0
   - 100.0
   - 150.0
   lowerBoundType: 2
-  binsNumber: 5
   costFuntionType: 3
   distribution: 4
   distributionParameters: 
   - 125.0
   - 12.0
   lowerBoundType: 1
binsSetsNumber: 2
itemsBySets: 
-  distribution: 1
   itemsNumber: 25
   rangeEnd: 100.0
   rangeInit: 1.0
-  itemsNumber: 25
   rangeEnd: 100.0
   rangeInit: 100.0
-  distribution: 4
   distributionParameters: 
   - 25.0
   - 12.0
   itemsNumber: 25
   rangeEnd: 100.0
   rangeInit: 1.0
itemsSetsNumber: 3
